In [20]:
import numpy as np

In [22]:
a = np.arange(15)

In [23]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
a =a.reshape(3,5)

In [36]:
a.shape

(3, 5)

In [37]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
a.dtype

dtype('int32')

In [39]:
a.dtype.name

'int32'

In [47]:
a=np.array([3,4.7,5.7,6])

In [48]:
a.dtype

dtype('float64')

In [55]:
c = np.array([[1,2],(4,5)], dtype = complex)

In [56]:
c.dtype

dtype('complex128')

In [57]:
c

array([[1.+0.j, 2.+0.j],
       [4.+0.j, 5.+0.j]])