# Welcome o numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,5,66363,7,8]],np.int64)

In [3]:
myarr

array([[    3,     4,     5, 66363,     7,     8]], dtype=int64)

In [4]:
myarr[0]

array([    3,     4,     5, 66363,     7,     8], dtype=int64)

In [5]:
myarr.shape

(1, 6)

In [6]:
myarr.dtype

dtype('int64')

#Array creation :Converton from other PYthon structures

In [11]:
listArray = np.array([[1,3,4],[3,4,6],[3,5,6]])

In [12]:
listArray

array([[1, 3, 4],
       [3, 4, 6],
       [3, 5, 6]])

In [13]:
listArray.dtype

dtype('int32')

In [14]:
listArray.size

9

In [15]:
listArray.shape

(3, 3)

In [18]:
np.array((23,34,45))

array([23, 34, 45])

In [21]:
zeros = np.zeros((2,5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,50,12)

In [25]:
lspace

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [26]:
np.empty((4,6))

array([[2.22809558e-312, 2.46151512e-312, 2.41907520e-312,
        2.05833592e-312, 6.79038654e-313, 6.79038653e-313],
       [2.37663529e-312, 2.05833592e-312, 2.41907520e-312,
        2.56761491e-312, 1.93101617e-312, 9.33678148e-313],
       [9.33678148e-313, 9.33678148e-313, 1.97345609e-312,
        1.93101617e-312, 9.33678148e-313, 9.33678148e-313],
       [1.97345609e-312, 1.93101617e-312, 9.33678148e-313,
        9.33678148e-313, 1.97345609e-312, 2.12199579e-313]])

In [27]:
np.empty_like(lspace)

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [30]:
arr = np.arange(99)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr=arr.reshape(3,33)

In [38]:
x =[[1,2,3],[4,5,6],[7,8,9]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
ar.sum(axis=0)

array([12, 15, 18])

In [42]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
ar.flat

In [46]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [47]:
ar.ndim

2

In [48]:
ar.size

9

In [49]:
ar.nbytes

36

In [51]:
one =np.array([1,2,34,64,34])

In [52]:
one.argmax()

3

In [53]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [54]:
ar.argmin()

0

In [55]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [56]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [57]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
ar2 =np.array([[3,4,5],
       [34,45,66],
       [34,56,76]])

In [62]:
ar+ar2

array([[ 4,  6,  8],
       [38, 50, 72],
       [41, 64, 85]])

In [64]:
ar2

array([[ 3,  4,  5],
       [34, 45, 66],
       [34, 56, 76]])

In [67]:
ar*ar2

array([[  3,   8,  15],
       [136, 225, 396],
       [238, 448, 684]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [69]:
ar.sum()

45

In [71]:
ar.min()

1

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [74]:
np.count_nonzero(ar)

9

In [76]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [77]:
import sys

In [78]:
ch_ar = [0,4,44,3]

In [ ]:
sys.getsizeof(1)